### PR TITLE
feat: add testimonials page

### PR DESCRIPTION
**Pull request by aryakaul**
Tried to add testimonials page but now when navigating to the /contact page it highlights 'Testimonials' in the topnav

### CODE REVIEW

**Comment by manzt** [comment]
hmm seriously weird. I'll take a closer look tomorrow afternoon!

**Comment by manzt** [comment]
Ok I fixed it... Seems to be a weird bug with Vitepress. The pages need different titles! 

**Note** I setup this netlify bot to build a preview of the site for each pull request. This way it will be easy to see a preview of the changes without needing to checkout and run locally.

**Comment by manzt** [comment]
Might I suggest removing the `Team` "feature" from the main landing page and leaving a link to that only in the nav bar. That way it's just "Contact" and "Testimonials" in the landing page.

**Review by manzt — APPROVED** [review]

**Comment by aryakaul** [comment]
awesome thanks for finding the fix!

**Pull request merged**
